---
- name: "Copy CheckMK apt plugin"
  become: true
  ansible.builtin.get_url:
    url: "https://10.70.1.151/cmk/check_mk/agents/plugins/mk_apt"
    dest: /usr/lib/check_mk_agent/plugins/mk_apt
    validate_certs: false
