---
- name: "Manage packages"
  vars:
    task_files: |
      {% set include_task_files = [] %}
      {% if packages_present is defined %}
      {%    set include_task_files = include_task_files + ['install.yml'] %}
      {% endif %}
      {% if packages_absent is defined %}
      {%    set include_task_files = include_task_files + ['uninstall.yml'] %}
      {% endif %}
      {% if packages_hold is defined %}
      {%    set include_task_files = include_task_files + ['hold.yml'] %}
      {% endif %}
      {% if packages_unhold is defined %}
      {%    set include_task_files = include_task_files + ['unhold.yml'] %}
      {% endif %}
      {{ include_task_files }}
  ansible.builtin.include_tasks: "package/{{ item }}"
  loop: "{{ task_files }}"
