---
- name: "Find installed Debian repositories"
  when: repos is not defined
  ansible.builtin.find:
    paths: /var/cache/ansible/apt_repos
    patterns: "*"
  register: repos

- name: "Set repos to list of installed Debian repositories"
  ansible.builtin.set_fact:
    repos: "{{ repos.files | map(attribute='path') | map('relpath', '/var/cache/ansible/apt_repos') | list | d([]) }}"

- name: "Manage Debian repositories"
  ansible.builtin.include_tasks: "repo/{{ item }}.yml"
  loop: "{{ repos + (repos_absent | d([])) }}"
  vars:
    rname: "{{ item }}"
