---
- when: repos is not defined
  block:
    - name: "Find installed Debian repositories"
      ansible.builtin.find:
        paths: /var/cache/ansible/apt_repos
        patterns: "*"
      register: find_repos

    - name: "Set repos to list of installed Debian repositories"
      ansible.builtin.set_fact:
        repos: "{{ find_repos.files | map(attribute='path') | map('relpath', '/var/cache/ansible/apt_repos') | list | d([]) }}"

- name: "Manage Debian repositories"
  ansible.builtin.include_tasks: "repo/{{ item }}.yml"
  loop: "{{ repos | d([]) + repos_absent | d([]) }}"
  vars:
    rname: "{{ item }}"
