---
- block:
    - name: "Manage gpg key for adoptopenjdk Debian repo"
      ansible.builtin.apt_key:
        url: "https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public"
        state: "{{ 'present' if 'adoptopenjdk' in repos else 'absent' }}"

    - name: "Manage adoptopenjdk debian repository"
      ansible.builtin.apt_repository:
        repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb {{ wanted_release }} main
        state: "{{ 'present' if 'adoptopenjdk' in repos else 'absent' }}"
        filename: adoptopenjdk
        update_cache: true
  environment:
    https_proxy: "{{ apt_proxy }}"
  tags:
    - repo
