---
- environment:
    https_proxy: "{{ apt_proxy | d('') }}"
  tags: repo
  become: true
  block:
    - name: "Set facts for {{ rname }} repository"
      when: wanted_release in debian_archive_dist
      vars:
        debian_archive_dist:
          - wheezy
          - jessie
          - stretch
      ansible.builtin.set_fact:
        debian_archived: true

    - name: "Configure Debian default repositories"
      become: true
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/debian.list
        content: |
          deb {{ repo_url }} {{ wanted_release }} {{ wanted_pools | join(' ') }}
          deb {{ repo_url }} {{ wanted_release }}-updates {{ wanted_pools | join(' ') }}
          deb {{ repo_url }} {{ wanted_release }}-backports {{ wanted_pools | join(' ') }}
          deb {{ repo_url_security }} {{ wanted_release }}-security {{ wanted_pools | join(' ') }}
      vars:
        repo_url: http://ftp.de.debian.org/debian
        repo_url_security: https://security.debian.org/debian-security
        wanted_pools: "{{ default_pools if ansible_distribution_major_version | int < 12 else default_pools + ['non-free-firmware'] }}"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: "Remove legacy repo files"
      become: true
      ansible.builtin.file:
        path: "{{ file }}"
        state: absent
      loop:
        - /etc/apt/sources.list
        - /etc/apt/sources.list.d/debian.sources
        - /etc/apt/sources.list.d/ftp_de_debian_org_debian.list
        - /etc/apt/sources.list.d/security_debian_org.list
        - /etc/apt/sources.list.d/security_debian_org_debian_security.list
        - /etc/apt/mirrors
      loop_control:
        loop_var: file
      ignore_errors: "{{ ansible_check_mode }}"

    - name: "Update package cache"
      become: true
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      ignore_errors: true

    - name: "Create ansible cache dir"
      become: true
      ansible.builtin.file:
        path: "/var/cache/ansible/apt_repos"
        state: directory
        owner: root
        group: root
        mode: "0755"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: "Store repo name to variable"
      become: true
      ansible.builtin.file:
        path: "/var/cache/ansible/apt_repos/{{ rname }}"
        state: touch
      changed_when: false
      ignore_errors: "{{ ansible_check_mode }}"
