---
- block:
    - name: "Manage gpg key for keydb Debian repo"
      ansible.builtin.apt_key:
        url: https://download.keydb.dev/open-source-dist/keyring.gpg
        state: "{{ 'present' if 'keydb' in repos else 'absent' }}"

    - name: "Manage keydb Debian repo"
      ansible.builtin.apt_repository:
        repo: deb https://download.keydb.dev/open-source-dist {{ ansible_distribution_release }} main
        state: "{{ 'present' if 'keydb' in repos else 'absent' }}"
        filename: keydb
        update_cache: true
  environment:
    https_proxy: "{{ apt_proxy }}"
  tags:
    - repo