---
- when: mariadb_version is defined
  block:
    - name: "Fail when mariadb_version not set"
      ansible.builtin.fail:
        msg: "mariadb_version not set"
      when: not (mariadb_version | d(false))

    - name: "Manage gpg key for MariaDB Debian repo"
      ansible.builtin.apt_key:
        url: https://mariadb.org/mariadb_release_signing_key.asc
        state: "{{ 'present' if 'mariadb' in repos else 'absent' }}"

    - name: "Find old repo files"
      ansible.builtin.find:
        paths: /etc/apt/sources.list.d
        patterns: "mariadb_mirror_*"
      register: old_repo_files

    - name: "Remove old repo files"
      ansible.builtin.file:
        path: "{{ old_repo_file.path }}"
        state: absent

      loop: "{{ old_repo_files.files | d([]) }}"
      loop_control:
        loop_var: old_repo_file

    - name: "Manage MariaDB Debian repo"
      ansible.builtin.apt_repository:
        repo: deb https://downloads.mariadb.com/MariaDB/mariadb-{{ mariadb_version }}/repo/debian {{ ansible_lsb.codename }} main
        state: "{{ 'present' if 'mariadb' in repos else 'absent' }}"
        filename: mariadb
        update_cache: true
  environment:
    https_proxy: "{{ apt_proxy }}"
  tags:
    - repo
