---
- block:
    - name: "Manage gpg key for Mysql Debian repo"
      ansible.builtin.apt_key:
        data: "{{ lookup('file', 'repo/debian/mysql.asc') }}"
        state: "{{ 'present' if 'mysql' in repos else 'absent' }}"

    - name: "Remove old repository file"
      ansible.builtin.file:
        state: absent
        path: "/etc/apt/sources.list.d/repo_mysql_com_apt_debian.list"

    - name: "Manage Mysql Debian repo"
      vars:
        wanted_dist: "{{ mysql_dist | default('mysql-tools') }}"
      ansible.builtin.apt_repository:
        repo: deb https://repo.mysql.com/apt/debian/ {{ wanted_release }} {{ wanted_dist }}
        state: "{{ 'present' if 'mysql' in repos else 'absent' }}"
        filename: mysql
        update_cache: true
  environment:
    https_proxy: "{{ apt_proxy }}"
  tags: repo