---
- block:
    - name: "Manage gpg key for openxchange Debian repo"
      ansible.builtin.apt_key:
        url: https://software.open-xchange.com/products/appsuite/stable/backend/Debian{{ ansible_distribution_release[0]|upper }}{{ ansible_distribution_release[1:] }}/Release.key
        state: "{{ 'present' if 'openxchange' in repos else 'absent' }}"

    - name: "Manage openxchange Debian UI repo"
      ansible.builtin.apt_repository:
        repo: deb https://software.open-xchange.com/products/appsuite/stable/appsuiteui/Debian{{ ansible_distribution_release[0]|upper }}{{ ansible_distribution_release[1:] }}/ /
        state: "{{ 'present' if 'openxchange' in repos else 'absent' }}"
        filename: software_open-xchange_com
        update_cache: true

    - name: "Manage openxchange Debian backend repo"
      ansible.builtin.apt_repository:
        repo: deb https://software.open-xchange.com/products/appsuite/stable/backend/Debian{{ ansible_distribution_release[0]|upper }}{{ ansible_distribution_release[1:] }}/ /
        state: "{{ 'present' if 'openxchange' in repos else 'absent' }}"
        filename: software_open-xchange_com
        update_cache: true
  environment:
    https_proxy: "{{ apt_proxy }}"
  tags:
    - repo
