---
- block:
    # DISABLE REPO
    - name: "Remove Percona MySQL Debian repo package"
      apt:
        name: percona-release
        state: absent
        update_cache: yes
      when: repo_nginx_disable | default(False)
    - name: "Remove percona mysql apt source files"
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - /etc/apt/sources.list.d/percona*
      when: repo_nginx_disable | default(False)
    # ENABLE REPO
    - name: "Install Percona MySQL Debian repo package"
      apt:
        name: https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb
      when: repo_percona_enable | default(False)
  when: ansible_distribution == "Debian"
  environment:
    https_proxy: "{{ apt_proxy }}"
  tags:
    - repo
