---
- environment:
    https_proxy: "{{ apt_proxy | d('') }}"
  tags: repo
  become: true
  block:
    - name: "Set facts for {{ rname }} debian repo"
      ansible.builtin.set_fact:
        key_url: "https://percona.com/downloads/deb-percona-keyring.gpg"
        key_file_asc: "/etc/apt/keyrings/{{ rname }}.asc"
        key_file: "/etc/apt/keyrings/{{ rname }}.gpg"
        repo_file: "/etc/apt/sources.list.d/{{ rname }}.list"
        repo_base:
          - "http://repo.percona.com/ps-{{ mysql_version | string |replace('.', '') }}/apt"
          - "http://repo.percona.com/tools/apt"
        legacy_repo_files:
          - /etc/apt/sources.list.d/percona-prel-release.list
          - /etc/apt/sources.list.d/percona-pxb-80-release.list
          - /etc/apt/sources.list.d/percona-telemetry-release.list

    - name: "Set repo file content for {{ rname }} debian repo"
      ansible.builtin.set_fact:
        repo_file_content: |
          {% for b in repo_base %}
          deb [signed-by={{ key_file }}] {{ b }} {{ wanted_release }} main
          {% endfor %}

    - name: "Call generic repo configuration tasks for {{ rname }} debian repo"
      ansible.builtin.include_tasks: repo/__generic__.yml
