---
- block:
    - name: "Manage gpg key for PHP (Sury) Debian repo"
      ansible.builtin.apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: "{{ 'present' if 'php' in repos else 'absent' }}"

    - name: "Manage PHP (Sury) Debian repo"
      ansible.builtin.apt_repository:
        repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
        state: "{{ 'present' if 'php' in repos else 'absent' }}"
        filename: php
        update_cache: true
  environment:
    https_proxy: "{{ apt_proxy }}"
  tags:
    - repo
