---
- environment:
    https_proxy: "{{ apt_proxy | d('') }}"
  tags: repo
  become: true
  block:
    - name: "Set facts for {{ rname }} debian repo"
      ansible.builtin.set_fact:
        key_url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
        key_file_asc: "/etc/apt/keyrings/{{ rname }}.asc"
        key_file: "/etc/apt/keyrings/{{ rname }}.gpg"
        repo_file: "/etc/apt/sources.list.d/ceph.list"
        repo_base: http://download.proxmox.com/debian/ceph-reef
        legacy_repo_files:
          - /etc/apt/sources.list.d/proxmox_ceph.list

    - name: "Set repo file content for {{ rname }} debian repo"
      ansible.builtin.set_fact:
        repo_file_content: |
          deb [signed-by={{ key_file }}] {{ repo_base }} {{ wanted_release }} no-subscription

    - name: "Call generic repo configuration tasks for {{ rname }} debian repo"
      ansible.builtin.include_tasks: repo/__generic__.yml
