---
- block:
    - name: "Manage gpg key for redis Debian repo"
      ansible.builtin.apt_key:
        url: https://packages.redis.io/gpg
        state: "{{ 'present' if 'redis' in repos else 'absent' }}"

    - name: "Manage redis Debian repo"
      ansible.builtin.apt_repository:
        repo: deb https://packages.redis.io/deb {{ wanted_release }} main
        state: "{{ 'present' if 'redis' in repos else 'absent' }}"
        filename: redis
        update_cache: true
  environment:
    https_proxy: "{{ apt_proxy }}"
  tags:
    - repo